apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: Cg==
    server: https://127.0.0.1:34071
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    namespace: youtube-app
    user: jenkins-sa
  name: jenkins-context
current-context: jenkins-context
kind: Config
users:
- name: jenkins-sa
  user: {}
