apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: youtube-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deploy-binding
  namespace: youtube-app
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
    namespace: youtube-app
roleRef:
  kind: ClusterRole
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
