apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deploy
  namespace: youtube-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deploy-role
  namespace: youtube-app
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments", "services", "pods", "configmaps"]
    verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deploy-binding
  namespace: youtube-app
subjects:
  - kind: ServiceAccount
    name: jenkins-deploy
    namespace: youtube-app
roleRef:
  kind: Role
  name: jenkins-deploy-role
  apiGroup: rbac.authorization.k8s.io
