apiVersion: v1
kind: Service
metadata:
  name: youtube-api
  namespace: youtube-app
spec:
  selector:
    app: youtube-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
